#!/usr/bin/env node
/**
 * Trace approved iconography PNGs → icon-art.ts (inline potrace paths).
 * Requires: magick, potrace
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
/** Raw PNG masters are local-only — set OTTO_ICON_DIR to your iconography folder. */
const ICON_DIR = process.env.OTTO_ICON_DIR;
if (!ICON_DIR) {
  console.error('Set OTTO_ICON_DIR to the directory containing approved icon PNGs (local only; not in public repo).');
  process.exit(1);
}
const OUT = join(__dirname, '../src/components/icon-art.ts');

/** UUID prefix → Icon key (14 approved PNGs). */
const MAP = {
  '9f655027-49c9-4123-aed6-e912eb4cfc61': 'chat',
  '838c22f8-a932-4d9e-99b9-e3693dbaad55': 'charter',
  'd74aa7ab-2092-4586-a2be-8f5811478876': 'standards',
  'bba82017-3d22-4001-ab06-535c4d3b132e': 'practices',
  'eadaa5fe-2d6c-491a-80a8-453757e4d021': 'routines',
  '7138b411-7861-48f2-a1d8-09fbf3747d23': 'curation',
  'c2494639-0eb5-4d24-8792-83d73072c728': 'receipts',
  '5e95bdc6-32dd-4890-97f3-08658e4f00b0': 'autonomy',
  '77513e3b-eb58-4c7c-808a-1abdfd1e3718': 'settings',
  'fe9ae131-31c5-4e33-b9c1-cc0d2629d567': 'owl',
  'af798576-1263-4a2f-aafa-43e6ca6fdf77': 'plus',
  '8787d7c9-cc66-4943-87dd-e6ce8c3942d0': 'panel',
  'a70b7358-fcc5-49d6-9849-78e573a7846b': 'theme',
  '8d20715a-f60d-4102-bda2-f5d0df9a81bc': 'send',
};

const trace = (pngPath) => {
  const tmp = mkdtempSync(join(tmpdir(), 'otto-icon-'));
  try {
    const pbm = join(tmp, 'in.pbm');
    const svg = join(tmp, 'out.svg');
    execFileSync('magick', [
      pngPath,
      '-alpha', 'off',
      '-colorspace', 'Gray',
      '-threshold', '50%',
      '-trim', '+repage',
      '-resize', '512x512',
      '-background', 'white',
      '-gravity', 'center',
      '-extent', '512x512',
      pbm,
    ], { stdio: 'pipe' });
    execFileSync('potrace', ['-s', '-O', '0.4', '-o', svg, pbm], { stdio: 'pipe' });
    const raw = readFileSync(svg, 'utf8');
    const gMatch = raw.match(/<g([^>]*)>([\s\S]*?)<\/g>/);
    if (!gMatch) throw new Error(`No <g> in ${pngPath}`);
    const transformMatch = gMatch[1].match(/transform="([^"]+)"/);
    if (!transformMatch) throw new Error(`No transform in ${pngPath}`);
    const paths = [...gMatch[2].matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
    if (!paths.length) throw new Error(`No paths in ${pngPath}`);
    return { transform: transformMatch[1], paths };
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
};

const entries = Object.entries(MAP).map(([uuid, key]) => {
  const png = join(ICON_DIR, `${uuid}.png`);
  const art = trace(png);
  return { key, ...art };
});

const body = entries.map(({ key, transform, paths }) => {
  const pathLines = paths.map((d) => `    { d: ${JSON.stringify(d)} },`).join('\n');
  return `  ${key}: {\n    transform: ${JSON.stringify(transform)},\n    paths: [\n${pathLines}\n    ],\n  },`;
}).join('\n');

const keys = entries.map((e) => `'${e.key}'`).join(' | ');

writeFileSync(OUT, `/** Generated by apps/desktop/scripts/trace-icons.mjs — do not hand-edit. */\n\nexport type IconArtKey = ${keys};\n\nexport type IconArt = {\n  transform: string;\n  paths: Array<{ d: string }>;\n};\n\nexport const iconArt: Record<IconArtKey, IconArt> = {\n${body}\n};\n`);

console.log(`Wrote ${OUT} (${entries.length} icons)`);
