// Readiness is real: generated by scripts/gen-readiness.mjs from local state.
import readinessData from './data/readiness.json';

// Readiness / setup model. The preview is file-backed only; nothing is wired to a runtime,
// so required runtime items honestly read "not wired" / "missing".
export type ReadyStatus = 'connected' | 'configured' | 'file' | 'missing' | 'not-wired';

export type ReadyItem = {
  key: string;
  label: string;
  status: ReadyStatus;
  detail: string;
  source?: string | null;
  action: string;
  required: boolean;
};

export const readiness = readinessData.items as ReadyItem[];
export const isReady = readinessData.ready as boolean;
export const requiredMissing = readiness.filter(
  (r) => r.required && (r.status === 'missing' || r.status === 'not-wired'),
);
