import type { SurfaceId } from '../components/Sidebar';

/**
 * Canonical UI copy — builder wires data; UX owns strings.
 *
 * Tier lexicon (Ship / Labs / Cut): docs/v1/ship-tier-matrix.md · docs/v1/labs.md
 * Design canon: docs/design/ (brand-style-guide.html, onboarding.md)
 * Labs shells: labsCopy · checks eyebrow = "culture ci" (Checks surface)
 *
 * Forbidden product words: beta, experimental, early access, unlock premium,
 * autonomous, guaranteed, fully handled, learned automatically, set it and forget it.
 * Loading: prefer thinking… over "working" theater.
 */
export type WebPreviewEmpty = {
  eyebrow: string;
  title: string;
  body: string;
  path?: string;
  next: string;
};

export type ListEmpty = {
  title: string;
  body: string;
};

export const webPreviewEmpty: Record<Exclude<SurfaceId, 'chat' | 'settings'>, WebPreviewEmpty> = {
  charters: {
    eyebrow: 'charters',
    title: 'Charters live in the desktop app.',
    body: 'Operating contracts link intent, acceptance criteria, runs, and receipts from ~/.otto/charters/.',
    path: '~/.otto/charters/',
    next: 'Open the packaged desktop app to create and track charters.',
  },
  standards: {
    eyebrow: 'standards',
    title: 'Standards load from canon files.',
    body: 'Explicit rules — what otto rewards, refuses, and does under pressure.',
    path: 'standards/',
    next: 'Open the desktop app to browse loaded Standards and precedents.',
  },
  practices: {
    eyebrow: 'practices',
    title: 'Practices are executable Standards.',
    body: 'Guardrails, invocations, and receipt requirements from practices/**/practice.yaml.',
    path: 'practices/',
    next: 'Open the desktop app to inspect practice specs and linked receipts.',
  },
  routines: {
    eyebrow: 'routines',
    title: 'Routines bundle repeated Practices.',
    body: 'Manual runs record receipts; recurring activation stays approval-gated.',
    path: 'routines/',
    next: 'Open the desktop app to run a routine manually.',
  },
  curation: {
    eyebrow: 'curation',
    title: 'Curation inbox is available in the desktop app.',
    body: 'Corrections become proposals. Accept ratifies canon; reject and defer leave canon unchanged.',
    path: '~/.otto/curation/proposals/',
    next: 'Open the packaged desktop app to inspect pending proposals.',
  },
  receipts: {
    eyebrow: 'receipts',
    title: 'Receipts prove what happened.',
    body: 'Durable proof records from ~/.otto/receipts/ — authority and evidence, not chat logs.',
    path: '~/.otto/receipts/',
    next: 'Open the desktop app to inspect receipt detail and blockers.',
  },
  autonomy: {
    eyebrow: 'autonomy',
    title: 'Autonomy policy loads locally.',
    body: 'Zones, doors, and Knowledge-informed routing — consequential actions stay gated.',
    path: '~/.otto/autonomy/',
    next: 'Open the desktop app to evaluate actions against policy.',
  },
  skills: {
    eyebrow: 'skills',
    title: 'Skills load from skill/**/SKILL.md.',
    body: 'Reusable capability packages — triggers and scope without secret sprawl.',
    path: 'skill/',
    next: 'Open the desktop app to browse loaded skills.',
  },
  knowledge: {
    eyebrow: 'knowledge',
    title: 'Knowledge registry is file-backed.',
    body: 'Model routing hints for Autonomy and ticket workers — not a second memory store.',
    path: '~/.otto/knowledge/',
    next: 'Open the desktop app to inspect registry entries.',
  },
  tickets: {
    eyebrow: 'tickets',
    title: 'Tickets orchestrate bounded worker slices.',
    body: 'Compile packets, spawn workers in worktrees, track status with receipts.',
    path: '~/.otto/tickets/',
    next: 'Open the desktop app to create and orchestrate tickets.',
  },
  channels: {
    eyebrow: 'channels',
    title: 'Channels are reachability surfaces.',
    body: 'Outbound sends stay approval-gated; inbound maps to proposals, not silent writes.',
    path: '~/.otto/channels/',
    next: 'Open the desktop app to configure channels.',
  },
  checks: {
    eyebrow: 'culture ci',
    title: 'Checks compile from ratified Standards.',
    body: 'File-backed regressions block done claims and one-way doors — failures surface here and in Chat.',
    path: '~/.otto/checks/',
    next: 'Open the desktop app to inspect active checks and block provenance.',
  },
  terminal: {
    eyebrow: 'terminal',
    title: 'Terminal opens from the desktop app.',
    body: 'Launch a local shell at the workspace root for agent workflows — not a web preview.',
    path: 'repo root',
    next: 'Open the packaged desktop app and choose Terminal in the workspace nav.',
  },
};

export const listEmpty: Partial<Record<SurfaceId, ListEmpty>> = {
  charters: {
    title: 'No charters yet',
    body: 'Create a charter when a bet needs explicit acceptance criteria and linked receipts.',
  },
  standards: {
    title: 'No Standards loaded',
    body: 'Add standards under standards/ or check loader skipped files below.',
  },
  practices: {
    title: 'No practices loaded',
    body: 'Add practice.yaml files under practices/ with valid guardrails.',
  },
  routines: {
    title: 'No routines loaded',
    body: 'Add routine.yaml under routines/ to bundle repeated practice invocations.',
  },
  curation: {
    title: 'No proposals',
    body: 'Corrections routed through Correct this → Curation will appear as needs_approval.',
  },
  receipts: {
    title: 'No receipts yet',
    body: 'Receipts emit when otto completes, blocks, or fails an action with proof.',
  },
  skills: {
    title: 'No skills loaded',
    body: 'Add SKILL.md files under skill/ to register capabilities.',
  },
  tickets: {
    title: 'No tickets yet',
    body: 'Create a ticket when work needs a bounded worker slice and acceptance mapping.',
  },
  channels: {
    title: 'No channels configured',
    body: 'Add a channel when otto needs a reachability surface with approval gates.',
  },
  checks: {
    title: 'No compiled checks yet',
    body: 'Ratify a Standard from Curation to compile a check, or seed checks under ~/.otto/checks on first launch.',
  },
};

export const toastCopy = {
  behaviorUpdated: 'Behavior updated',
  behaviorUpdatedMemory: 'Behavior updated · memory writeback',
  behaviorUpdatedBody: (target: string, summary: string, receiptId: string) =>
    `${target}: ${summary} · receipt ${receiptId}`,
  proposalAccepted: 'Proposal accepted',
  proposalRejected: 'Proposal rejected',
  proposalDeferred: 'Proposal deferred',
  decisionBlocked: 'Decision blocked',
  proposalCreated: 'Proposal created',
  openCuration: 'Open in Curation',
  openReceipt: 'Open receipt',
  checkActive: 'Check active',
} as const;

export const chatCopy = {
  sessionTitle: 'What should we work on?',
  sessionBodyNotReady: 'Finish runtime setup above, then send your first message.',
  starterPrompts: [
    'Help me think through the next step.',
    'Draft a short plan I can react to.',
    'Turn a rough idea into a ratifiable Standard.',
  ] as const,
  composerNotReadyHint: 'Finish setup above to send · your draft is saved locally',
  composerSendBlockedTitle: 'Send is unavailable until the runtime is ready',
  starterBlockedTitle: 'Finish runtime setup above to use starter prompts',
  queuePending: (count: number) => `${count} waiting to send`,
  queueFailed: (count: number) => `${count} couldn't send`,
  queueMixed: (pending: number, failed: number) =>
    `${pending} waiting · ${failed} failed`,
  queueNextSummary: (summary: string, next: string) => `${summary} · next: ${next}`,
  queueClearAll: 'Clear queue',
  queueRetryAll: 'Retry all',
  queueShow: 'Show',
  queueHide: 'Hide',
  queueRetryOne: 'Retry',
  queueSendNow: 'Send now',
  queueEdit: 'Recall',
  queueRecalledToast: 'Recalled to composer. Still queued until you send or remove.',
  queueViewFull: 'View',
  queueHideFull: 'Hide',
  queueRemoveOne: 'Remove queued message',
  queuePillNext: 'next',
  queuePillWaiting: 'waiting',
  queuePillFailed: 'failed',
  queuePillPosition: (position: number) => `#${position}`,
  truncatedOnReload: (hiddenChars: number) =>
    hiddenChars > 0
      ? `Shortened on reload (${hiddenChars.toLocaleString()} chars hidden).`
      : 'Shortened on reload.',
  truncatedShowFull: 'Show full message',
  truncatedLoading: 'Loading…',
  errorWhoLabel: "Couldn't complete",
  errorDetailsSummary: 'Technical details',
  runtimeConnectingEyebrow: 'starting runtime',
  runtimeConnectingTitle: 'Connecting to Letta…',
  runtimeConnectingBody: 'Booting your local agent session. This usually takes a few seconds. If this hangs, export a diagnostics bundle from Settings.',
  runtimeNotReadyEyebrow: 'runtime not ready',
  runtimeNotReadyTitle: "otto can't connect yet",
  runtimeNotReadyBody: 'Check Settings for Letta connection and required setup. Export diagnostics from Settings to attach evidence to an issue.',
  runtimeNoAgentBody: 'Open Letta Desktop once to create a default agent, or set an Agent ID override in Settings.',
  runtimeNoAgentSubtitle: 'Set up a local Letta agent',
  exportDiagnostics: 'Export diagnostics',
  diagnosticsHint: 'Attach the bundle path to GitHub issues/PRs. Secrets and chat content are redacted.',
  workingPulse: 'thinking…',
  selectModelTitle: 'Select model',
  showLegacyModels: 'Show legacy models',
  hideLegacyModels: 'Hide legacy models',
  customModelAction: 'Use custom handle…',
  customModelPrompt: 'Custom model handle',
  customModelApply: 'Apply',
  modelDeprecatedBadge: 'deprecated',
  modelLegacyBadge: 'legacy',
  autoModelResolvedPrefix: 'Resolved',
  reasoningTitle: 'Reasoning',
  pickerRetry: 'Retry',
  pickerOpenSettings: 'Open Settings',
  correctThis: 'Correct this',
  correctThisHint: 'Turn this moment into changed future behavior',
  correctionDefault: 'This response should change — describe the behavior you want instead.',
  proposeFromCorrection: 'Propose from correction',
  proposeFromCorrectionHint: 'Becomes a proposal — nothing changes until you approve it.',
  correctThisModalTitle: 'Correct this',
  createProposal: 'Create proposal',
  cancel: 'Cancel',
  futureBehavior: 'Describe the behavior you want next time',
  ticketCommandHint: 'Commands: compile ticket <slug> <objective> · orchestrate ticket <slug> · check ticket <slug> · merge ticket <slug> · status workers',
  onboardingHint: 'Send your first message — otto writes a Receipt when work completes with proof.',
  onboardingReceiptHint: 'First turn recorded — open Receipts to inspect the proof record.',
  onboardingSkip: 'Skip setup',
  onboardingViewReceipts: 'View Receipts',
  copyMarkdown: 'Copy Markdown',
  copyMarkdownHint: 'Copy this conversation as Markdown for handoff or docs',
  copyMarkdownEmpty: 'Nothing to copy yet.',
  copyMarkdownDone: 'Conversation copied',
  copyMarkdownDoneBody: 'Markdown is on your clipboard. Local paths and likely secrets were redacted.',
  copyMarkdownFailed: 'Could not copy conversation',
  memoryOn: 'Letta memory on',
  memoryOff: 'Letta memory off',
  memoryLinkTitle: 'Open Memory observatory in Settings',
} as const;

export const previewCopy = {
  eyebrow: 'preview',
  panelLabel: 'Artifact preview',
  toggleLabel: 'Preview',
  toggleHint: 'Toggle artifact preview pane (⌘⇧P)',
  openMessage: 'Open preview',
  openMessageHint: 'Render this message in the preview pane',
  close: 'Close preview pane',
  resizeHandle: 'Resize preview pane',
  htmlFrameTitle: 'HTML artifact preview',
  emptyEyebrow: 'preview',
  emptyTitle: 'Nothing selected yet',
  emptyBody: 'Open preview on a message, or click an HTML code block, to render agent output here.',
  emptyNext: 'Use Preview on a reply, or ⌘⇧P to show this pane.',
  userMessageTitle: 'Your message',
  assistantMessageTitle: 'otto reply',
  codeBlockTitle: 'Code block',
} as const;

export const onboardingCopy = {
  badge: 'Local-first · desktop',
  eyebrow: 'OTTO',
  welcomeTitle: 'The behavior layer for persistent agents.',
  welcomeBody: 'otto ships as one desktop app. It records what your agent relied on before it acted — and changes the next run only when you ratify it.',
  authorityLine: 'The human ratifies. otto records the proof.',
  primaryStart: 'Get started →',
  secondarySample: 'See what Receipts will prove',
  advancedExisting: 'Advanced: existing Letta install',
  skip: 'Skip',
  progressWelcome: 'Welcome',
  progressConnect: 'Connect',
  progressRun: 'Run',
  progressReceipt: 'Receipt',
  modeTitle: 'How should otto connect?',
  modeLede: 'Pick one path. Otto uses one primary agent per workspace — change connection later in Settings.',
  modeEmbeddedTitle: 'This Mac',
  modeEmbeddedBody: 'One app — embedded Letta runtime. Provider keys stay in Letta.',
  modeEmbeddedBadge: 'Recommended',
  modeExistingTitle: 'Existing Letta install',
  modeExistingBody: 'Advanced: connect otto to a Letta you already run (local URL + agent ID). Not required for This Mac.',
  modeContinue: 'Continue →',
  connectTitle: 'Connect your runtime',
  connectLede: 'otto auto-discovers your local runtime and default agent. One primary agent per workspace — readiness rows below show the exact blocker. Provider keys stay in Letta — otto never stores them.',
  connectOpenSettings: 'Open Settings',
  connectContinue: 'Continue →',
  connectRetry: 'Retry status',
  runTitle: 'Run one behavior loop',
  runLede: 'Send a first message and watch otto do real work — then inspect the Receipt.',
  runGoChat: 'Go to Chat',
  runChips: [
    'Summarize what otto can do in this workspace',
    'Run a reversible check on this repo',
  ] as const,
  receiptTitle: 'First Receipt',
  receiptLede: 'A Receipt shows what the workspace relied on before it acted — sources, limits, and review signature.',
  receiptOpen: 'Open Receipts',
  receiptDone: 'Done',
  sampleOnlyNote: 'Sample path — does not count as live proof from your workspace.',
  connectedOk: 'otto is connected to Letta.',
  legacyDockEyebrow: 'Getting started',
} as const;

export const loaderCopy = {
  eyebrow: 'loader',
  validationPill: 'validation',
  skippedTitle: (count: number, noun: string) =>
    `${count} malformed ${noun}${count === 1 ? '' : 's'} skipped`,
} as const;

export const permissionCopy = {
  modalTitle: 'Permission required',
  windowTitle: 'Permission',
  windowLede: 'Active permission route, pending tool gates, and recent decisions.',
  eyebrow: 'approval gate',
  modeLabel: 'Permission mode',
  routeLabel: 'Active route',
  pendingTitle: 'Pending request',
  recentTitle: 'Recent decisions',
  recentEmpty: 'No permission decisions this session yet.',
  sessionAllowedTitle: 'Allowed for session',
  sessionAllowedEmpty: 'No tools session-allowed yet.',
  riskLabel: 'Risk',
  actionLabel: 'Action',
  scopeOnce: 'once',
  scopeSession: 'session',
  allowOnce: 'Allow once',
  allowSession: 'Allow for session',
  deny: 'Deny',
  denyPlaceholder: 'Optional reason if you deny',
  deniedByUser: 'Denied by operator',
  correctThis: 'Correct this',
  interactiveNote: 'This tool needs a richer answer than yes/no — allow or deny for now; full interactive flow ships separately.',
} as const;

export const projectCopy = {
  windowTitle: 'Project',
  windowLede: 'Active folder, otto home profile, and live session context.',
  eyebrow: 'workspace context',
  projectRoot: 'Project folder',
  ottoHome: 'otto home',
  profileHome: 'Profile home',
  lettaState: 'Letta state',
  sessionTitle: 'Session',
  threadLabel: 'Thread',
  agentLabel: 'Agent',
  conversationLabel: 'Conversation',
  transportLabel: 'Transport',
  switchTitle: 'Switch project',
  switchBlocked: 'In-app project switching is not available in v1.',
  loading: 'Loading workspace context…',
  unavailable: 'Project context is available in the desktop app only.',
} as const;

export const threadCopy = {
  pinnedLabel: 'Pinned',
  recentsLabel: 'Recents',
  empty: 'No conversations yet.',
  pinnedEmpty: 'Nothing pinned yet. Pin any conversation in Recents to keep it here.',
  recentsEmpty: 'Recent conversations appear here.',
  pin: 'Pin conversation — keep in Pinned',
  unpin: 'Unpin conversation — move to Recents',
  archive: 'Archive conversation',
  rename: 'Rename conversation',
  renameHint: 'Double-click a title to rename',
  restore: 'Restore to recents',
  archivedLabel: 'Archived',
  archivedEmpty: 'Archived conversations appear here.',
  showArchived: 'Show archived',
  hideArchived: 'Hide archived',
  reorderHint: 'Drag to reorder within Pinned or Recents.',
} as const;

export const curationCopy = {
  eyebrow: 'curation',
  title: 'Curation decides what compounds.',
  lede: 'Classify proposed changes by consequence — auto-apply reversible work, ratify doors, write receipts.',
  inkHeadline: 'Own reversible work.',
  inkHeadlineMuted: 'Gate consequential work.',
  inkSub: 'One engine owns classification so door doctrine cannot drift.',
  statPending: 'Needs ratification',
  statDecided: 'Decided',
  filterPending: 'Pending',
  filterDecided: 'Decided',
  filterAll: 'All',
  emptyPendingTitle: 'Nothing waiting on you',
  emptyPendingBody: 'When otto proposes a behavior change, it lands here for ratification before canon moves.',
  emptyDecidedTitle: 'No decided proposals yet',
  emptyDecidedBody: 'Accepted, rejected, and deferred proposals appear here with their decision record.',
  ratificationTitle: 'Ratify this change',
  ratificationLede: 'Accept applies canon when a target is set. Reject and defer write receipts without changing behavior.',
  accept: 'Accept',
  reject: 'Reject',
  defer: 'Defer',
  approvalsEyebrow: 'decision records',
  approvalsTitle: 'Curation decisions are records',
  approvalsLede: 'Emitted by Curation — not a peer subsystem. Each decision ties proposal, outcome, and receipt.',
  approvalsEmpty: 'No decision records yet. Accept, reject, or defer a consequential proposal to emit one.',
  memoryBadge: 'memory writeback',
  metaStorage: 'Proposal storage',
  pathChipLabel: 'proposal file',
  classificationEyebrow: 'classification',
  evidenceEyebrow: 'evidence',
  zoneRisk: 'risk',
  zoneGate: 'gate',
  zoneCanon: 'canon',
  zoneReason: 'reason',
  changelogEyebrow: 'behavior changelog',
  changelogTitle: 'What changed this week',
  changelogLede: 'Culture changes only — ratified proposals, constitution edits, autonomy policy. Not chat activity.',
} as const;

export const chartersCopy = {
  eyebrow: 'operating contracts',
  title: 'Charters bind intent to proof.',
  lede: 'Explicit bets with acceptance criteria, linked runs, and receipts — not chat goals.',
  inkLead: 'Intent without proof',
  inkMuted: 'is a wish list.',
  inkSub: 'The office decides. Otto records the review.',
  explainerEyebrow: 'what is a charter',
  explainerBody:
    'A charter is the operating contract for a long-running goal: objective, acceptance criteria, approval gates, and receipt proof. Use it for multi-step, approval-gated work. One-off nits and polish belong in GitHub Issues.',
  issuesRelationship:
    'Charter owns the operating contract. GitHub Issues own implementation tasks and per-PR merge gates.',
  modelEyebrow: 'object model',
  modelIntent: 'Intent',
  modelCharter: 'Charter',
  modelState: 'State',
  modelReceipt: 'Receipt',
  continueButton: 'Continue charter',
  proofOk: 'proof linked',
  proofPending: 'proof pending',
  statTotal: 'Charters',
  statActive: 'Active',
  statComplete: 'Complete',
  metaLabel: 'Create charter',
  createEyebrow: 'new charter',
  createTitle: 'Operating contract',
  objectiveLabel: 'Objective',
  objectivePlaceholder: 'Represent an explicit goal/run contract',
  criterionLabel: 'Acceptance criterion',
  criterionPlaceholder: 'A concrete proof condition',
  slugLabel: 'Slug',
  createButton: 'Create charter',
  loadingList: 'Loading charters…',
  loadingTitle: 'Loading charter…',
  selectTitle: 'Select a charter',
  selectBody: 'Charter state appears after creation.',
  detailEyebrow: 'charter detail',
  acEyebrow: 'acceptance criteria',
  approvalEyebrow: 'approval boundary',
  linkedRunsEyebrow: 'linked runs',
  linkedReceiptsEyebrow: 'linked receipts',
  attachEyebrow: 'attach run / receipt',
  runIdPlaceholder: 'run id',
  receiptIdPlaceholder: 'receipt id',
  attachButton: 'Attach',
  statusEyebrow: 'update status',
  statusSummaryPlaceholder: 'change summary',
  updateButton: 'Update',
  changesEyebrow: 'changes',
  noRunLinked: 'No run linked',
  noReceiptLinked: 'No receipt linked',
  completeRequiresReceipt: (missingIds: string) =>
    `Complete requires receipt proof on every acceptance criterion (${missingIds} missing).`,
} as const;

export const standardsCopy = {
  eyebrow: 'case law',
  title: 'Culture needs case law.',
  lede: 'Explicit rules — what otto rewards, refuses, and does under pressure.',
  inkLead: 'Until a Standard costs something,',
  inkMuted: 'it is still a poster.',
  inkSub: 'The first real Review should let No Fake Done block a premature completion.',
  statLoaded: 'Standards',
  statActive: 'Active',
  metaLabel: 'Registry',
  ratificationOwner: 'Owner',
  ratificationAutoApply: 'Auto apply',
  loadingTitle: 'Loading standards…',
  conflictEyebrow: 'conflict · case law',
  conflictTieBreaker: 'Tie-breaker:',
  conflictProposeCuration: 'Propose a Curation Standards change instead of improvising in chat.',
  filterAll: 'All',
  filterActive: 'Active',
  filterDraft: 'Draft',
  filterDeprecated: 'Superseded',
  filterDomainAll: 'All domains',
  searchPlaceholder: 'Search standards, rationale, examples…',
  searchNoMatch: 'No matching Standards',
  selectTitle: 'Select a Standard',
  selectBody: 'Pick an explicit rule to see what otto rewards, refuses, and how case law resolves tension with other Standards.',
  conflictNoneHint: 'No registered tension map entry for this Standard.',
  tensionMapEyebrow: 'tension map',
  antiPatternsEyebrow: 'anti-patterns',
  domainLabel: 'Domain',
  canonBodyEyebrow: 'canon · rationale',
  curationPathEyebrow: 'curation path',
  curationPathBody: 'Propose changes through Curation; Sebastian ratifies registry updates — never auto-apply.',
} as const;

export const practicesCopy = {
  eyebrow: 'executable culture',
  title: 'Practices are executable culture.',
  lede: 'Guardrails, invocations, and receipt requirements — promotion stays approval-gated.',
  inkLead: 'A Practice exists only if behavior should repeat.',
  inkMuted: 'No ritual sludge.',
  inkSub: 'If it does not create durable state, evidence, or better decisions, it is not a Practice.',
  statLoaded: 'Practices',
  statWithReceipts: 'With proof',
  statRunnable: 'Runnable',
  metaLabel: 'Practice storage',
  curationGate: 'Practice promotion, activation, and publish remain approval-gated.',
  noInvocations: 'No invocations declared.',
} as const;

export const routinesCopy = {
  eyebrow: 'compound behavior',
  title: 'Routines make Practices compound.',
  lede: 'Manual runs write receipts immediately; recurring activation stays approval-gated.',
  inkLead: 'Attention is a one-way door.',
  inkMuted: 'Recurring output must earn it.',
  inkSub: 'A routine that would not be missed should be pruned or redesigned.',
  statLoaded: 'Routines',
  statActive: 'Active',
  metaLabel: 'Routine files',
} as const;

export const autonomyCopy = {
  eyebrow: 'orchestration policy',
  title: 'Autonomy owns the steps.',
  lede: 'Zones, doors, and Knowledge-informed routing — consequential actions always escalate.',
  inkLead: 'Otto owns orchestration.',
  inkMuted: 'Sebastian owns consequences.',
  inkSub: 'Workers are sessions, not separate identities.',
  statZones: 'Zones',
  statDoors: 'Doors',
  metaLabel: 'Policy file',
  evaluateEyebrow: 'check an action',
  evaluateHint: 'Classification writes an autonomy receipt — blocked when approval is required.',
  evaluatePlaceholder: 'Describe the proposed action…',
  evaluateButton: 'Evaluate action',
  evaluatingButton: 'Evaluating…',
  doorsEyebrow: 'consequential doors',
  zoneAutonomous: 'autonomous',
  zoneApproval: 'approval',
  evalApprovalRequired: 'Approval required',
  evalMayProceed: 'May proceed autonomously',
  evalRoutingPrefix: 'Knowledge routing ·',
  evalReceiptPrefix: 'receipt ·',
  safeAutoMergeLabel: 'safe_auto_merge',
  routingKnowledgeHint: 'Full registry and model table live on Knowledge.',
} as const;

export const skillsCopy = {
  eyebrow: 'capability packages',
  title: 'Skills provide capability.',
  lede: 'Reusable packages with triggers and scope — culture sets the standard, skills provide the how.',
  inkLead: 'Culture sets the standard.',
  inkMuted: 'Skills provide the capability.',
  inkSub: 'Password management is a Skill; Winning is a Standard.',
  statLoaded: 'Skills',
  metaLabel: 'Skill directory',
  triggersEyebrow: 'triggers',
  noTriggers: 'No triggers parsed',
  loadingTitle: 'Loading skills…',
} as const;

export const knowledgeCopy = {
  eyebrow: 'AI Frontier',
  title: 'Expectations must update.',
  lede: 'Model routing hints for Autonomy and ticket workers — not a second memory store.',
  inkLead: 'Autonomy should track actual capability.',
  inkMuted: 'Not inherited human-era assumptions.',
  inkSub: 'Stale caution can be as wrong as reckless speed.',
  statModels: 'Models',
  statRoles: 'Routing roles',
  metaLabel: 'Registry path',
  cogneeEyebrow: 'derived recall',
  cogneeTitle: 'Graph recall (Cognee)',
  cogneeLoopback: (baseUrl: string, checkedAt?: string) =>
    `Loopback only · ${baseUrl}${checkedAt ? ` · checked ${checkedAt}` : ''}`,
  cogneeNoCapture: 'No capture receipt yet — run scripts/cognee-capture.sh after Cognee is ready.',
  cogneeRefresh: 'Refresh health',
  cogneeRecallSmoke: 'Recall smoke',
  cogneeNoCitations: 'No citations — index capture or start Cognee daemon first.',
  zoneLastCapture: 'last capture',
  zoneKinds: 'kinds',
  zoneDocs: 'docs',
  zoneEntities: 'entities',
  zoneUnknown: 'unknown',
  zonePath: 'path',
  zoneCitation: 'citation',
  pgvectorEyebrow: 'semantic recall',
  pgvectorTitle: 'pgvector (optional)',
  loadingTitle: 'Loading knowledge…',
  registryNotFoundTitle: 'Registry not found',
  registryNotFoundBody: (path: string) =>
    `Could not read ${path}. Knowledge routing falls back until the registry exists.`,
  registryProposedPrefix: 'Registry status is proposed — routing assignments are defaults, not ratified policy.',
  routingEyebrow: 'routing assignments',
  modelsEyebrow: 'models',
} as const;

export const ticketsCopy = {
  eyebrow: 'worker slices',
  title: 'Tickets define the slice.',
  lede: 'Compile bounded packets, orchestrate workers in worktrees, track status with receipts.',
  inkLead: 'Charters define the bet.',
  inkMuted: 'Tickets define the slice.',
  inkSub: 'One worktree per ticket keeps implementation parallel and reviewable.',
  statOpen: 'Open',
  statReview: 'In review',
  statTotal: 'Tickets',
  metaLabel: 'Ticket storage',
  createEyebrow: 'new ticket',
  createTitle: 'Worker slice',
  objectiveLabel: 'Objective',
  objectivePlaceholder: 'Objective for the worker slice…',
  slugLabel: 'Slug',
  slugPlaceholder: 'Optional slug (defaults from objective)',
  compile: 'Compile ticket',
  orchestrate: 'Orchestrate in worktree',
  noChecks: 'No checks',
} as const;

export const paperclipIntakeCopy = {
  eyebrow: 'intake',
  title: 'Paperclip context (read-only)',
  lede: 'Imported work_state from Paperclip — display-only. Paperclip status is never otto Done.',
  notConnectedTitle: 'Paperclip not connected',
  notConnectedBody: 'Connect through the approval door (021). No mock rows appear here.',
  connect: 'Connect Paperclip',
  confirmConnect: 'Approve connect',
  sync: 'Sync now',
  lastSync: (at: string) => `Last sync · ${new Date(at).toLocaleString()}`,
  noSyncYet: 'Connected — no sync yet',
  syncErrorTitle: 'Sync error',
  emptySyncTitle: 'No imported tasks yet',
  emptySyncBody: 'Run sync after 021 writes export.json or set OTTO_PAPERCLIP_EXPORT.',
  activeEyebrow: 'active tasks',
  blockedEyebrow: 'blocked tasks',
  artifactsEyebrow: 'recent artifacts',
  openInPaperclip: 'Open in Paperclip',
  approvalRequired: 'Approval required before enabling the connector.',
  storageLabel: 'Adapter storage',
} as const;

export const channelsCopy = {
  eyebrow: 'reachability',
  title: 'Channels reach the human.',
  lede: 'Discord is the ambient console backend in v1. Outbound sends are external side effects.',
  inkLead: 'Channels notify and collect input.',
  inkMuted: 'They do not replace the record.',
  inkSub: 'A tool being present is never authorization to use it.',
  statConfigured: 'Channels',
  statEnabled: 'Enabled',
  metaLabel: 'Channel config',
  selectTitle: 'Select a channel',
  selectBody: 'Pick a reachability surface to review address, status, and send gates.',
  enabledLabel: 'enabled',
  disabledLabel: 'disabled',
  addressLabel: 'Address',
  outboundLabel: 'Outbound sends',
  outboundApproval: 'Approval required',
  outboundDirect: 'Direct send allowed',
  configFileLabel: 'Config file',
  approvalNote: 'External side effects on this channel stay gated until the operator approves.',
  loadingTitle: 'Loading channels…',
} as const;

export const labsCopy = {
  eyebrow: 'labs',
  title: 'Labs features',
  lede: 'Experimental paths stay off until you turn Labs on. Ship-tier surfaces work without Labs.',
  masterLabel: 'Enable Labs',
  masterWarning: 'Labs may break or change without notice. Use on a workspace you can reset.',
  masterHint: 'When off, Labs-tier nav items show coming soon.',
  featureEnableLabel: 'Enable feature',
  matrixLink: 'See docs/v1/ship-tier-matrix.md for tier mapping.',
  shippedBadge: 'Shipped',
  previewBadge: 'Coming soon',
  enableLabel: 'Enable in this workspace',
  comingSoonEyebrow: 'coming soon',
  comingSoonTitle: (label: string) => `${label} is not enabled yet`,
  comingSoonNext: 'Turn on Labs and this feature in Settings → General → Labs when you are ready to try it.',
  comingSoonWorkspaceNext: 'Chat and Settings are live today. This workspace surface is still wiring up for v1.',
  openLabs: 'Open Labs settings',
  loadingTitle: 'Loading workspace features…',
  loadingBody: 'Reading Labs settings from this profile.',
  blockedEyebrow: 'labs blocked',
  blockedTitle: (label: string) => `${label} needs setup`,
  blockedNext: 'Resolve the setup requirement, then retry this Labs feature.',
  openSettings: 'Open Settings',
  startSidecar: 'Check sidecar health',
  cogneeBlockedTitle: 'Graph recall is off',
  cogneeBlockedBody: 'Enable Knowledge (Cognee) in Settings → General → Optional recall, then start the local sidecar. See docs/cognee.md — no mock graph rows.',
  pgvectorBlockedTitle: 'Vector recall is off',
  pgvectorBlockedBody: 'Enable pgvector in Settings → General → Optional recall and start local Postgres. Files remain canon.',
  channelsBlockedTitle: 'Outbound sends are contract-only',
  channelsBlockedBody: 'Channel definitions load from files. Live bot sends stay off until outbound is configured and approved.',
  channelsBlockedNext: 'Review channel config when you are ready to enable outbound sends.',
} as const;

export const settingsCopy = {
  eyebrow: 'settings',
  pageTitle: 'Settings',
  pageLede: 'Connection, workspace defaults, and diagnostics when something breaks.',
  title: 'General',
  lede: 'How otto connects to Letta and where workspace data lives.',
  inkLead: 'Connection truth lives here.',
  inkMuted: 'Not in chat claims.',
  inkSub: 'Readiness gates Chat and irreversible actions until required items are configured.',
  statRuntime: 'Runtime',
  statRequired: 'Required gaps',
  metaReadiness: 'Readiness detail',
  tabGeneral: 'General',
  tabDisplay: 'Display',
  tabProviders: 'Models & agents',
  tabMemory: 'Memory',
  tabCulture: 'Culture',
  tabDiagnostics: 'Diagnostics',
  generalTitle: 'General',
  generalLede: 'Letta connection, workspace paths, and everyday defaults.',
  connectionTitle: 'Letta connection',
  connectionLede: 'otto discovers your local Letta web server and default agent automatically. Embedded mode uses the bundled CLI — no separate Letta Desktop install. Override only when discovery picks the wrong runtime.',
  connectionAdvancedSummary: 'Advanced overrides',
  connectionAdvancedHint: 'Use when auto-detect picks the wrong URL or agent.',
  optionalRecallTitle: 'Optional recall',
  optionalRecallLede: 'Derived recall sidecars. Off by default — files and Letta memory remain canon.',
  onboardingTitle: 'Onboarding',
  onboardingLede: 'Replay the first-run walkthrough anytime.',
  onboardingStart: 'Start onboarding',
  onboardingStartToastTitle: 'Onboarding started',
  onboardingStartToastBody: 'Welcome back — the first-run walkthrough is open.',
  readinessTitle: 'Readiness',
  readinessLede: 'What must be true before Chat and irreversible actions unlock.',
  readinessChecking: 'Checking runtime…',
  readinessDetail: 'Show readiness detail',
  readinessConnected: 'Connected — live Letta session',
  readinessNotReady: 'Setup required — Chat stays disabled until required items are configured.',
  providersTitle: 'Models & agents',
  providersLede: 'Connect Letta and external agent CLIs. Provider keys stay in Letta — otto mirrors status and next actions only.',
  agentsTitle: 'Agent connections',
  agentsLede: 'Where to connect Cursor, Codex, Claude Code, and the local Letta runtime.',
  agentsLettaName: 'Letta runtime',
  agentsLettaDetail: 'Primary agent for Chat. Configure connection mode in General.',
  agentsCursorName: 'Cursor agent CLI',
  agentsCursorDetail: 'Install the Cursor CLI and sign in — otto routes model picks through Letta, not Cursor directly.',
  agentsCodexName: 'Codex (ChatGPT subscription)',
  agentsCodexDetail: 'Auth via Letta provider mirror — use Model providers below or Open Letta.',
  agentsClaudeName: 'Claude (API or Pro/Max)',
  agentsClaudeDetail: 'Anthropic keys and subscriptions are managed in Letta.',
  agentsActionOpenLetta: 'Open Letta',
  agentsActionGeneral: 'Connection settings',
  agentsActionDocs: 'Read setup docs',
  memoryTitle: 'Memory observatory',
  memoryLede: 'Read-only view of Letta core-memory blocks. Writeback goes through Curation.',
  cogneeEnableLabel: 'Enable Cognee sidecar',
  pgvectorSettingsLede: 'Local vector recall store. Env-gated — see docs/pgvector.md.',
  primaryAgentLabel: 'Primary agent',
  primaryAgentHint: 'One default agent per workspace — memory continuity is the product.',
  primaryAgentOpenLetta: 'Open in Letta',
  advancedAgentsTitle: 'Advanced',
  advancedAgentsLede: 'Second agents need a real isolation boundary (ADR 093).',
  isolatedAgentBoundaryLabel: 'Isolation boundary',
  isolatedAgentBoundaryPlaceholder: 'Select why this agent must be isolated',
  isolatedAgentLabelField: 'Agent label (optional)',
  isolatedAgentLabelPlaceholder: 'e.g. finance-ops',
  isolatedAgentCreate: 'Create isolated agent',
  isolatedAgentCreateBusy: 'Creating…',
  isolatedAgentCreateSuccess: 'Isolated agent created',
  isolatedAgentCreateSuccessBody: 'Receipt recorded. Chat still uses your primary agent.',
  isolatedAgentListTitle: 'Isolated agents',
  isolatedAgentListEmpty: 'No isolated secondary agents yet.',
  isolatedAgentReceiptNote: 'Receipt',
  isolatedAgentStandardsNote: 'Shared Standards canon ratify is blocked for isolated agents in v1.',
  connectionModeLabel: 'Connection mode',
  connectionEmbedded: 'Embedded (bundled CLI + local web server)',
  connectionExisting: 'Existing local Letta',
  connectionCloud: 'Cloud remote',
  conversationSortLabel: 'Conversation order',
  conversationSortHint: 'Default sort for threads you have not dragged. Manual order always wins.',
  conversationSortRecent: 'Most recent activity',
  conversationSortCreated: 'Newest first',
  connectionLocalUrlLabel: 'Local Letta URL · advanced override',
  connectionLocalUrlPlaceholder: 'Auto-detect local runtime',
  connectionAgentIdLabel: 'Agent ID · advanced override',
  connectionAgentIdPlaceholder: 'Auto-detect current/default agent',
  connectionSaveBusy: 'Connecting…',
  connectionSaveIdle: 'Save overrides & reconnect',
  connectionFailedPrefix: 'Connection failed:',
  providerMirrorNote: 'Provider auth is managed by Letta. otto never stores or reads back API keys.',
  providerMirrorLoading: 'Reading provider mirror…',
  providerApiKeyPresent: 'API key on file (write-only)',
  providerApiKeyMissing: 'No API key on file',
  providerSubmitKey: 'Save API key (write-only)',
  onboardingReplayTitle: 'First-run walkthrough',
  onboardingReplayHint: 'Clears the first-run flag and opens Welcome immediately — no relaunch needed.',
  readinessReadyFallback: 'otto is ready to work',
  readinessGroupRuntime: 'Runtime & identity',
  readinessGroupCapabilities: 'Capabilities',
  readinessGroupSurfaces: 'v1 surfaces',
  systemHealthTitle: 'System health',
  systemHealthLede: 'Live checks for renderer, runtime, session, memory, permissions, queue, scheduler, and build marker.',
  systemHealthRefresh: 'Refresh health',
  systemHealthOk: 'All required checks passing',
  systemHealthNotOk: 'One or more checks need attention',
  systemHealthLoading: 'Running health checks…',
  systemHealthImpact: 'Impact',
  systemHealthNext: 'Next',
  diagnosticsGroupTitle: 'Diagnostics & health',
  diagnosticsGroupLede: 'Runtime checks, readiness gates, logs, and export bundles when something looks wrong.',
  localOnlyFootnote: 'v1 is local-only: This Mac bundles and runs an embedded Letta runtime by default; Existing local Letta is an advanced path. Provider keys stay in Letta. Cloud auth stays an advanced path.',
  diagnosticsTitle: 'Export bundle',
  diagnosticsLede: 'One-click redacted bundle for blank, stale, slow, or disconnected runtime failures.',
  diagnosticsExport: 'Export diagnostics bundle…',
  diagnosticsExportDone: 'Diagnostics bundle exported',
  diagnosticsCommand: 'DevTools: await window.otto.diagnostics.export()',
  diagnosticsOpenLogs: 'Open logs folder',
  diagnosticsOpenRuns: 'Open runs folder',
  diagnosticsRefreshLogs: 'Refresh logs',
  diagnosticsLogsTitle: 'Recent logs (redacted)',
  diagnosticsLogsFolder: 'Logs folder',
  diagnosticsRunsFolder: 'Runs folder',
  diagnosticsLogsEmpty: 'No log tail yet — run a chat turn or refresh after reproducing the issue.',
  memoryConnectWarn: 'Connect Letta in General before expecting live blocks.',
  memorySearchPlaceholder: 'Search blocks…',
  memoryNoMatch: 'No memory blocks match. Connect an agent or adjust search.',
  dreamingTitle: 'Dreaming / sleep-time',
  dreamingLede: 'Background memory reflection while the agent is idle — same trigger model as Letta /sleeptime.',
  dreamingTriggerLabel: 'Trigger event',
  dreamingTriggerOff: 'Off',
  dreamingTriggerStepCount: 'Step count',
  dreamingTriggerCompaction: 'Compaction event',
  dreamingStepCountLabel: 'Step count',
  dreamingStepCountHint: 'Run sleep-time reflection every N agent steps.',
  dreamingMemfsWarn: 'Sleep-time reflection requires the memory filesystem (memfs) to be enabled for this agent. Enable OTTO_MEMFS=1 when your backend supports it, then reconnect.',
  dreamingSaved: 'Dreaming settings saved',
  sectionMemory: 'Memory observatory',
  sectionCulture: 'Culture import',
  workspaceTitle: 'Workspace & permissions',
  workspaceLede: 'Where otto resolves repo data and which tools are allowed for this chat session.',
  workspaceRepoTitle: 'Active folder',
  workspaceRepoHint: 'Repo root for practices, standards, and recall sidecars. Set OTTO_ROOT to override.',
  workspaceHomeTitle: 'otto home',
  workspaceHomeHint: 'Local config and secrets. Override with OTTO_HOME.',
  workspaceReveal: 'Reveal in Finder',
  workspaceCopyPath: 'Copy path',
  workspaceCopyToastTitle: 'Path copied',
  workspaceCopyToastBody: 'Workspace path copied to clipboard.',
  permissionRouteTitle: 'Permission route',
  permissionRouteHint: 'Tools allowed for this session via Chat “Allow for session”. Cleared on new chat or restart.',
  permissionRouteEmpty: 'No session allowances yet — approvals happen in Chat when a tool runs.',
  permissionRouteClear: 'Clear session allowances',
  permissionRouteClearToastTitle: 'Session allowances cleared',
  permissionRouteClearToastBody: 'Future tool runs will prompt again until you allow them.',
  displayTitle: 'Appearance',
  displayLede: 'Theme controls how otto renders in the workspace shell. Density and chat layout prefs ship later.',
  displayThemeLabel: 'Theme',
  displayThemeHint: 'Light is the default warm-paper look. System follows macOS appearance.',
  displayThemeLight: 'Light',
  displayThemeDark: 'Dark',
  displayThemeSystem: 'System',
} as const;

/** ADR 093 boundary enum — keep aligned with `electron/isolated-agent.ts`. */
export const isolatedAgentBoundaryOptions = [
  { id: 'different_owner', label: 'Different human owner' },
  { id: 'different_authority', label: 'Different authority level' },
  { id: 'different_secrets_tools', label: 'Different secrets or tools' },
  { id: 'different_schedule_channel', label: 'Different schedule or channel' },
  { id: 'different_mission', label: 'Different long-running mission' },
  { id: 'strong_isolation', label: 'Strong isolation need' },
] as const;

export const receiptsCopy = {
  eyebrow: 'proof trail',
  title: 'What was proven',
  lede: 'Authority, evidence, and outcome — not a log dump. Each receipt states who decided and what changed.',
  statTotal: 'Receipts',
  statSuccess: 'Succeeded',
  statBlocked: 'Blocked',
  statFailed: 'Failed',
  searchPlaceholder: 'Search summary, action, subject…',
  filterAll: 'All',
  selectTitle: 'Select a receipt',
  selectBody: 'Pick a proof record to see authority, evidence, and blockers.',
  loadingTitle: 'Loading proof…',
  emptyTitle: 'No proof yet',
  emptyBody: 'Send or block a chat turn, ratify a proposal, or run a practice — otto writes a receipt when behavior completes.',
  sampleLede: 'Inspect the sample structure below — it is not live proof from your workspace.',
  runsEyebrow: 'execution records',
  runsTitle: 'Runs',
  noMatchTitle: 'No matching receipts',
  noMatchBody: 'Clear the search or status filter to see the full proof trail.',
  authorityEyebrow: 'authority & outcome',
  evidenceEyebrow: 'evidence',
  recordMeta: 'Receipt record',
  debugMeta: 'Raw contract (debug)',
  inlineLabel: 'Receipt',
  openInReceipts: 'Open in Receipts',
  filterAuthorityAll: 'All authority',
  filterAuthorityHuman: 'Human',
  filterAuthorityAutonomy: 'Autonomy',
  filterAuthorityRuntime: 'Runtime',
} as const;

/** Culture CI checks surface — list via checks.list IPC. */
export const checksCopy = {
  eyebrow: 'culture ci',
  title: 'Checks',
  lede: 'File-backed checks compile from Standards and Practices. Blocks surface here and in Chat when a check fails.',
  inkLead: 'Every correction can become',
  inkMuted: 'a regression test',
  inkSub: 'Ratify in Curation; enforcement shows up here and in Chat — not as silent logs.',
  emptyTitle: 'No compiled checks yet',
  emptyBody: 'Ratify a Standard from Curation to compile a check, or seed checks under ~/.otto/checks on first launch.',
  statActive: 'Active checks',
  statDoneClaim: 'Done claim',
  statOneWayDoor: 'One-way door',
  statLastRun: 'Last run',
  lastRunNone: '—',
  lastRunPass: 'pass',
  lastRunFail: 'fail',
  runCounts: 'Runs',
  metaLabel: 'Registry & provenance',
  blockEyebrow: 'check failed',
  blockPill: 'BLOCK',
  openReceipt: 'Open receipt',
  openStandard: 'Open standard',
  loadingTitle: 'Loading checks…',
  zoneTrigger: 'trigger',
  zoneSource: 'source',
  zoneInspect: 'inspect',
  zoneCompiled: 'compiled',
  zoneCompiledAt: 'compiled at',
  zoneStandard: 'standard',
} as const;

export const cultureCiCopy = {
  compileHint: 'Use check ticket <slug> in Chat to evaluate done-claim checks before merge.',
  blockHint: 'Failed checks block irreversible actions until mapped proof is attached or autonomy allows override.',
} as const;

export const memoryWritebackCopy = {
  eyebrow: 'memory writeback',
  title: 'Approve memory write',
  lede: 'This change would persist to Letta memory. Approve only when the summary matches what you want remembered.',
  targetEyebrow: 'target',
  approve: 'Approve write',
  deny: 'Deny',
} as const;

export const cultureSettingsCopy = {
  eyebrow: 'culture',
  title: 'Constitution & export',
  lede: 'Read and amend workspace culture. Export a portable bundle without secrets or Letta memory.',
  loadingTitle: 'Loading constitution…',
  openConstitution: 'Open constitution.yaml',
  exportCulture: 'Export culture…',
  importPreview: 'Import preview (dry-run)',
  amendTitle: 'Amend constitution (YAML)',
  amendSave: 'Save amendment',
  exportDone: 'Culture bundle exported',
  writebackGate: 'Memory changes only after you accept in Curation.',
} as const;

export const terminalCopy = {
  eyebrow: 'terminal',
  title: 'Local shell',
  body: 'Open your system terminal at the workspace root — for git, tasks, and local agent workflows.',
  open: 'Open in Terminal',
  opening: 'Opening…',
  openFailed: 'Could not open a terminal window.',
  workspaceLabel: 'Workspace root',
  workspaceLoading: 'Resolving…',
  lastOpenedLabel: 'Last opened',
  inkLead: 'Opens your system terminal at',
  inkMuted: 'the workspace root',
  embeddedNote: 'An embedded PTY inside otto is planned; this surface opens Terminal.app (or your platform default) today.',
} as const;
